language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tax/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true tax/docker-practice npm run test

after_success:
  # - docker build -t tax/docker-practice .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-st
  # - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # - docker push tax/docker-practice
